Sil\Bundle\EcommerceBundle\Entity\CustomerGroup:
    type: mappedSuperclass
    table: sil_ecommerce_customer_group
    # oneToMany:
    #     customers:
    #         targetEntity: Sylius\Component\Core\Model\Customer
    #         mappedBy: group
