Sil\Bundle\EcommerceBundle\Entity\CustomerGroup:
    type: entity
    # oneToMany:
    #     customers:
    #         targetEntity: Sylius\Component\Customer\Model\CustomerInterface
    #         mappedBy: group
