Sil\Bundle\EcommerceBundle\Entity\Invoice:
    type: entity
    fields:
        number:
            type: string
            nullable: false
            unique: true
        mimeType:
            type: string
            nullable: true
        size:
            type: integer
            nullable: true
        file:
            type: text
            nullable: false
        total:
            type: integer
            nullable: false
        type:
            type: integer
            nullable: false

    manyToOne:
        order:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\Order
            inversedBy: invoices
            cascade: ["persist"]
            joinColumn:
                name: order_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
