Sil\Bundle\EcommerceBundle\Entity\Order:
    type: mappedSuperclass

    oneToMany:
        invoices:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\Invoice
            mappedBy: order
            cascade: [ persist, remove ]
            orphanRemoval: true
