Sil\Bundle\EcommerceBundle\Entity\OrderItem:
    type: mappedSuperclass
    table: sil_ecommerce_order_item
    fields:
        bulk:
            type: boolean
            nullable: false
            options:
                default: false
