Sil\Bundle\EcommerceBundle\Entity\ProductVariant:
    type: mappedSuperclass
    fields:
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
