Sil\Bundle\EcommerceBundle\Entity\ProductVariant:
    type: mappedSuperclass
    table: sil_ecommerce_product_variant
    fields:
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
