Sil\Bundle\EcommerceBundle\Entity\ProductImage:
    type: mappedSuperclass
    table: sil_ecommerce_product_image
    manyToOne:
        realFile:
            targetEntity: Sil\Bundle\MediaBundle\Entity\FileInterface
            joinColumn:
                name: real_file_id
                referencedColumnName: id
                onDelete: CASCADE
            fetch: EAGER
    manyToMany:
        productVariants:
            targetEntity: Sylius\Component\Product\Model\ProductVariantInterface
            orphanRemoval: true
            inversedBy: images
            joinTable:
                name: sil_ecommerce_product_image__product_variant
                joinColumns:
                    joinColumn:
                        name: image_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    joinColumn:
                        name: variant_id
                        referencedColumnName: id
                        onDelete: CASCADE
