Sil\Bundle\EcommerceBundle\Entity\ProductImage:
    type: entity
    manyToOne:
        realFile:
            targetEntity: Sil\Bundle\MediaBundle\Entity\File
            joinColumn:
                name: real_file_id
                referencedColumnName: id
                onDelete: CASCADE
            fetch: EAGER
    manyToMany:
        productVariants:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\ProductVariant
            orphanRemoval: true
            inversedBy: images
            joinTable:
                name: sil_ecommerce_productimage__productvariants
                joinColumns:
                    joinColumn:
                        name: image_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    joinColumn:
                        name: variant_id
                        referencedColumnName: id
                        onDelete: CASCADE
