Sil\Bundle\EcommerceBundle\Entity\SalesJournalItem:
    type: entity
    repositoryClass: Sil\Bundle\EcommerceBundle\Repository\SalesJournalItemRepository
    fields:
        operationDate:
            type: datetime
            nullable: false
        account:
            type: string
            length: 64
            nullable: false
        label:
            type: string
            length: 255
            nullable: false
        debit:
            type: integer
            nullable: false
        credit:
            type: integer
            nullable: false
    manyToOne:
        order:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\Order
        invoice:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\Invoice
        payment:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\Payment
