Sil\Bundle\EcommerceBundle\Entity\TaxRate:
    type: mappedSuperclass
    table: sil_ecommerce_tax_rate
    blast:
        loggable: true
        #    manyToOne:
#        zone:
#            targetEntity: Sylius\Component\Addressing\Model\ZoneInterface
#            joinColumn:
#                name: zone_id
#                referencedColumnName: id
#                nullable: false
