Sil\Bundle\CRMBundle\Entity\Organism:
    type: entity
#    repositoryClass: Sil\Bundle\EmailCRMBundle\Entity\Repository\OrganismRepository
    fields:
        emailCanonical:
            type: string
            nullable: false
            unique: true
    oneToOne:
        user:
            targetEntity: Sylius\Component\Core\Model\ShopUser
            mappedBy: customer
            cascade: [all]

    oneToMany:
        orders:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\Order
            mappedBy: customer
            cascade: [persist, remove]
        addresses:
            targetEntity: Sil\Bundle\CRMBundle\Entity\Address
            mappedBy: customer
            cascade: [ persist ]

    manyToOne:
        group:
            targetEntity: Sil\Bundle\EcommerceBundle\Entity\CustomerGroup
            inversedBy: customers
