# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

    librinfo_ecommerce.admin.product:
        class: Librinfo\EcommerceBundle\Admin\ProductAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\Product, LibrinfoEcommerceBundle:ProductCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductAdmin:edit.html.twig ] ]

    librinfo_ecommerce.admin.product_variant:
        class: Librinfo\EcommerceBundle\Admin\ProductVariantAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductVariant, LibrinfoEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_variant_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]

    librinfo_ecommerce_option.admin.product:
        class: Librinfo\EcommerceBundle\Admin\ProductOptionAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductOption, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_option_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce_option_value.admin.product:
        class: Librinfo\EcommerceBundle\Admin\ProductOptionValueAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductOptionValue, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_option_value_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.product_attribute:
        class: Librinfo\EcommerceBundle\Admin\ProductAttributeAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductAttribute, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_attribute_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
    
    librinfo_ecommerce.admin.customer:
        class: Librinfo\EcommerceBundle\Admin\CustomerAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoCRMBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
        calls:
            - [setManager, [@doctrine.orm.entity_manager]]
            - [setCodeGenerator, [@librinfo_crm.code_generator.customer]]
            - [ setTemplate, [edit, LibrinfoCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]