services:

    sil_ecommerce.admin.product:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Product, SilEcommerceBundle:ProductCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.product.product
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductAdmin:edit.html.twig ] ]

    sil_ecommerce.admin.product_variant:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductVariantAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\ProductVariant, SilEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.product.product_variant
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]

    sil_ecommerce.admin.product_variant_embedded:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductVariantEmbeddedAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\ProductVariant, SilEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.product.product_variant
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]

    sil_ecommerce_option.admin.product:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductOptionAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\ProductOption, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.product.product_option
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce_option_value.admin.product:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductOptionValueAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\ProductOptionValue, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.product.product_option_value
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.product_attribute:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductAttributeAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\ProductAttribute, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.product.product_attribute
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.customer:
        class: Sil\Bundle\EcommerceBundle\Admin\CustomerAdmin
        arguments: [~, %sylius.model.customer.class%, SilCRMBundle:OrganismAdmin]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Customers Relationship Management
              label: sil.ecommercebundle.admin.crm.customer
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce
        calls:
            - [setCodeGenerator, ['@sil_crm.code_generator.customer']]
            - [ setTemplate, [edit, SilCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, SilCRMBundle:OrganismAdmin:show.html.twig]]

    sil_ecommerce.admin.order:
        class: Sil\Bundle\EcommerceBundle\Admin\OrderAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Order, SilEcommerceBundle:OrderCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.order
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce
        calls:
            - [ setTemplate, [edit, SilEcommerceBundle:OrderAdmin/Create:create.html.twig]]

    sil_ecommerce.admin.payment:
        class: Sil\Bundle\EcommerceBundle\Admin\PaymentAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Payment, SilEcommerceBundle:PaymentCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.payment
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.payment_method:
        class: Sil\Bundle\EcommerceBundle\Admin\PaymentMethodAdmin
        arguments: [~, Sylius\Component\Core\Model\PaymentMethod, SilEcommerceBundle:PaymentCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.payment_method
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.sales_journal:
        class: Sil\Bundle\EcommerceBundle\Admin\SalesJournalAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\SalesJournalItem, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.sales_journal
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.customer_group:
        class: Sil\Bundle\EcommerceBundle\Admin\CustomerGroupAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\CustomerGroup, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Customers Relationship Management
              label: sil.ecommercebundle.admin.customer_group
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.channel_pricing:
        class: Sil\Bundle\EcommerceBundle\Admin\ChannelPricingAdmin
        arguments: [~, Sylius\Component\Core\Model\ChannelPricing, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.Channel
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.tax_rate:
        class: Sil\Bundle\EcommerceBundle\Admin\TaxRateAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\TaxRate, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.TaxRate
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.tax_category:
        class: Sil\Bundle\EcommerceBundle\Admin\TaxCategoryAdmin
        arguments: [~, Sylius\Component\Taxation\Model\TaxCategory, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.TaxCategory
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.zone:
        class: Blast\Bundle\CoreBundle\Admin\GenericAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Zone, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.Zone
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.taxon:
        class: Sil\Bundle\EcommerceBundle\Admin\TaxonAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Taxon, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.Taxon
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.invoice:
        class: Sil\Bundle\EcommerceBundle\Admin\InvoiceAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Invoice, SilEcommerceBundle:InvoiceCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.Invoice
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.channel:
        class: Sil\Bundle\EcommerceBundle\Admin\ChannelAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\Channel, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.channel
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.shipping_method:
        class: Sil\Bundle\EcommerceBundle\Admin\ShippingMethodAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\ShippingMethod, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.shipping_method
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

#    sil_ecommerce.admin.shipping_category:
#        class: Sil\Bundle\EcommerceBundle\Admin\ShippingCategoryAdmin
#        arguments: [~, Sylius\Component\Shipping\Model\ShippingCategory, BlastCoreBundle:CRUD]
#        tags:
#            - name: sonata.admin
#              manager_type: orm
#              group: admin
#              label: sil.ecommercebundle.admin.shipping_category
#              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.shipping_method_translation:
        class: Sil\Bundle\EcommerceBundle\Admin\ShippingMethodTranslationAdmin
        arguments: [~, Sylius\Component\Shipping\Model\ShippingMethodTranslation, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.shipping_method_translation
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce

    sil_ecommerce.admin.shop_user:
        class: Sil\Bundle\EcommerceBundle\Admin\ShopUserAdmin
        arguments: [~, Sylius\Component\Core\Model\ShopUser, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.ecommercebundle.admin.shop_user
              label_translator_strategy: blast_core.label.strategy.sil_ecommerce
