# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

    librinfo_product.admin.product:
        class: Librinfo\ProductBundle\Admin\ProductAdmin
        arguments: [~, Librinfo\ProductBundle\Entity\Product, LibrinfoProductBundle:ProductAdmin]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_product.admin.product_variant:
        class: Librinfo\ProductBundle\Admin\ProductVariantAdmin
        arguments: [~, Librinfo\ProductBundle\Entity\ProductVariant, LibrinfoProductBundle:ProductVariantAdmin]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_variant_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoProductBundle:ProductVariantAdmin:edit.html.twig ] ]

    librinfo_product_option.admin.product:
        class: Librinfo\ProductBundle\Admin\ProductOptionAdmin
        arguments: [~, Librinfo\ProductBundle\Entity\ProductOption, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_option_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_product_option_value.admin.product:
        class: Librinfo\ProductBundle\Admin\ProductOptionValueAdmin
        arguments: [~, Librinfo\ProductBundle\Entity\ProductOptionValue, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_option_value_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_product.admin.product_attribute:
        class: Librinfo\ProductBundle\Admin\ProductAttributeAdmin
        arguments: [~, Librinfo\ProductBundle\Entity\ProductAttribute, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_attribute_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
#        calls:
#            - [ setTemplate, [ edit, BlastCoreBundle:CRUD:base_edit.html.twig ] ]
#            - [ setTemplate, [ list, BlastCoreBundle:CRUD:base_list.html.twig ] ]
#            - [ setTemplate, [ show, BlastCoreBundle:CRUD:base_show.html.twig ] ]

