# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    blast:

##########
# PRODUCT
##########

        Librinfo\EcommerceBundle\Entity\Product:
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    form_group_general:
                        '':
                            name:
                                label: librinfo.label.product_name
                            code:
                                label: librinfo.label.product_code
                            enabled: boolean
                            description: ~
                            options:
                                label: librinfo.label.product_options
                            shortDescription: ~
                            metaKeywords: ~
                            metaDescription: ~
                        show_group_availability:
                            available:
                                type: boolean
                            availableOn: ~
                            availableUntil: ~
                    show_tab_variants:
                        '':
                            variants:
                                admin_code: librinfo_ecommerce.admin.product_variant
                    form_tab_history:
                        form_group_history:
                            createdAt: ~
                            updatedAt: ~
                    _options:
                        tabsOrder: [form_group_general, show_tab_variants, form_tab_history]

            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name:
                                type: text
                                label: librinfo.label.product_name
                            code:
                                label: librinfo.label.product_code
                            enabled: boolean
                            description:
                                type: textarea
                                required: false
                            shortDescription:
                                type: textarea
                                required: false
                            metaKeywords:
                                type: text
                                required: false
                            metaDescription:
                                type: textarea
                                required: false
                            options:
                                label: librinfo.label.product_options
                                required: false
                            availableOn:
                                type: sonata_type_datetime_picker
                                required: false
                                dp_use_current: false
                                dp_pick_time: true
                            availableUntil:
                                type: sonata_type_datetime_picker
                                required: false
                                dp_use_current: true
                                dp_pick_time: true
                    form_tab_variants:
                        '':
                            variants:
                                type: sonata_type_collection
                                label: false
                                by_reference: false
                                type_options:
                                    btn_add: false
                                    delete_options:
                                        type: checkbox
                                        type_options:
                                            mapped: false
                                            required: false
                                required: true    # if not true, child form fields cannot be required (why ??)
                                _options:
                                    edit: inline
                                    inline: table
                                    admin_code: librinfo_ecommerce.admin.product_variant
                    _options:
                        tabsOrder: [form_group_general, form_tab_history]

            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name:
                        identifier: true
                        label: librinfo.label.product_name
                    code:
                        identifier: true
                        label: librinfo.label.product_code
                    enabled:
                        type: boolean
                    available:
                        type: boolean
                    _options:
                        fieldsOrder:
                            - code
                            - name
                            - enabled
                            - available
                    _actions:
                        variants:
                            template: 'LibrinfoEcommerceBundle:CRUD:list__action_variants.html.twig'
                    _export_formats:
                        csv: [code, name, available]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    translations.name:
                        label: librinfo.label.product_name
                    code:
                        label: librinfo.label.product_code
                    translations.description:
                        label: librinfo.label.description
                    translations.shortDescription:
                        label: librinfo.label.short_description
                    translations.metaKeywords:
                        label: librinfo.label.meta_keywords
                    translations.metaDescription:
                        label: librinfo.label.meta_description
                    enabled: ~
#                    available: ~
                    _options:
                        fieldsOrder:
                            - code
                            - translations.name


##################
# PRODUCT VARIANT
##################

        Librinfo\EcommerceBundle\Entity\ProductVariant:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    form_group_general:
                        '':
                            product:
                                admin_code: librinfo_ecommerce.admin.product
                            name:
                                label: librinfo.label.product_variant_name
                            code:
                                label: librinfo.label.product_variant_code
                            price: ~
                            optionValues:
                                template: 'LibrinfoEcommerceBundle:ProductVariantAdmin:show_field_optionvalues.html.twig'

                        show_group_stock:
                            onHand: ~
                            onHold: ~
                            tracked:
                                type: boolean
                                label: librinfo.label.tracked_stock
                        show_group_availability:
                            available:
                                type: boolean
                            availableOn: ~
                            availableUntil: ~
                        show_group_properties:
                            width: ~
                            height: ~
                            depth: ~
                            weight: ~
                    form_tab_history:
                        form_group_history:
                            createdAt: ~
                            updatedAt: ~
                    _options:
                        tabsOrder: [form_group_general, form_tab_history]
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            product:
                                type: sonata_type_model_autocomplete
                                property: [translations.name, code]
                                read_only: true
                                _options:
                                    admin_code: librinfo_ecommerce.admin.product
                            name:
                                label: librinfo.label.product_variant_name
                            code:
                                label: librinfo.label.product_variant_code
                            price: ~
                            optionValues:
                                property: fullName
                            _options:
                                fieldsOrder: [product, name, code, price, optionValues]
                        form_group_stock:
                            onHand:
                                required: false
                            onHold:
                                required: false
                            tracked:
                                label: librinfo.label.tracked_stock
                        form_group_availability:
                            availableOn:
                                type: sonata_type_datetime_picker
                                required: false
                                dp_use_current: false
                                dp_pick_time: true
                            availableUntil:
                                type: sonata_type_datetime_picker
                                required: false
                                dp_use_current: true
                                dp_pick_time: true
                        form_group_properties:
                            width: ~
                            height: ~
                            depth: ~
                            weight: ~
                    _options:
                        tabsOrder: [form_group_general, form_tab_history]
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    code:
                        identifier: true
                        label: librinfo.label.product_variant_code
                    name:
                        identifier: true
                        label: librinfo.label.product_variant_name
                    product:
                        admin_code: librinfo_ecommerce.admin.product
                    available:
                        type: boolean
                    price: ~
                    optionValues:
                        associated_property: fullCode
                    onHand: ~
                    onHold: ~
                    tracked:
                        type: boolean
                        label: librinfo.label.tracked_stock
                    _options:
                        fieldsOrder:
                            - code
                            - name
                            - product
                            - available
                            - price
                            - optionValues
                            - onHand
                            - onHold
                            - tracked
                    _export_formats:
                        csv: [code, name, available]
                        xls: csv
                        json: csv
                        xml: csv
            # FILTER
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name:
                        label: librinfo.label.product_variant_name
                    code:
                        label: librinfo.label.product_variant_code
                    product.code: ~
                    _options:
                        fieldsOrder:
                            - name
                            - code
                            - product.code



####################
# PRODUCT ATTRIBUTE
####################

        Sylius\Component\Product\Model\ProductAttribute:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            name: ~
                            type: ~
                    show_tab_history:
                        show_group_history:
                            createdAt: ~
                            updatedAt: ~
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            name:
                                type: text
                            type:
                                type: Sylius\Bundle\AttributeBundle\Form\Type\AttributeTypeChoiceType
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    code: ~
                    name: ~
                    type: ~
            # FILTERS
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    translations.name:
                        label: librinfo.label.name
                    type: ~
                    storageType: ~
                    createdAt: ~
                    updatedAt: ~

####################
# PRODUCT OPTION
####################

        Librinfo\EcommerceBundle\Entity\ProductOption:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            name: ~
                    show_tab_values:
                        '':
                            values: ~
                    show_tab_history:
                        show_group_history:
                            createdAt: ~
                            updatedAt: ~
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            name:
                                type: text
                    form_tab_values:
                        '':
                            values: ~
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    code:
                        identifier: true
                    name:
                        identifier: true
            # FILTERS
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    translations.name:
                        label: librinfo.label.name
                    createdAt: ~
                    updatedAt: ~


####################
# PRODUCT OPTION VALUE
####################

        Librinfo\EcommerceBundle\Entity\ProductOptionValue:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            value: ~
                            option:
                                label: librinfo.label.product_option
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            value:
                                type: text
                            option:
                                label: librinfo.label.product_option
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    code:
                        identifier: true
                    value: ~
                    option:
                        label: librinfo.label.product_option
            # FILTERS
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    translations.value:
                        label: librinfo.label.value
