# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    blast:

##########
# PRODUCT
##########

        Librinfo\ProductBundle\Entity\Product:
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    form_group_general:
                        '':
                            name: ~
                            code: ~
                        form_tab_availability:
                            available:
                                type: boolean
                            availableOn: ~
                            availableUntil: ~
                    form_tab_history:
                        form_group_history:
                            createdAt: ~
                            updatedAt: ~
                            createdBy: ~
                            updatedBy: ~

            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name:
                                type: text
                            code: ~
                            availableOn:
                                type: sonata_type_datetime_picker
                                required: false
                                dp_use_current: false
                                dp_pick_time: true
                            availableUntil:
                                type: sonata_type_datetime_picker
                                required: false
                                dp_use_current: true
                                dp_pick_time: true

            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name:
                        identifier: true
                    code:
                        identifier: true
                    available:
                        type: boolean
                    _options:
                        fieldsOrder:
                            - code
                            - name
                            - available
                    _export_formats:
                        csv: [code, name, available]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    translations.name:
                        label: librinfo.label.name
                    code: ~
#                    available:
#                        type: boolean
                    _options:
                        fieldsOrder:
                            - code
#                            - name
#                            - available



####################
# PRODUCT ATTRIBUTE
####################

        Sylius\Component\Product\Model\ProductAttribute:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            name: ~
                            type: ~
                    show_tab_history:
                        show_group_history:
                            createdAt: ~
                            updatedAt: ~
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            name:
                                type: text
                            type:
                                type: Sylius\Bundle\AttributeBundle\Form\Type\AttributeTypeChoiceType
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    code: ~
                    name: ~
                    type: ~
            # FILTERS
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    translations.name:
                        label: librinfo.label.name
                    type: ~
                    storageType: ~
                    createdAt: ~
                    updatedAt: ~

####################
# PRODUCT OPTION
####################

        Librinfo\ProductBundle\Entity\ProductOption:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            name: ~
                    show_tab_values:
                        '':
                            values: ~
                    show_tab_history:
                        show_group_history:
                            createdAt: ~
                            updatedAt: ~
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            name:
                                type: text
                    form_tab_values:
                        '':
                            values: ~
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    code:
                        identifier: true
                    name:
                        identifier: true
            # FILTERS
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    translations.name:
                        label: librinfo.label.name
                    createdAt: ~
                    updatedAt: ~


####################
# PRODUCT OPTION
####################

        Librinfo\ProductBundle\Entity\ProductOptionValue:
            # SHOW
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            value: ~
                            option:
                                label: librinfo.label.product_option
            # FORM
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            code: ~
                            value:
                                type: text
                            option:
                                label: librinfo.label.product_option
            # LIST
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    code:
                        identifier: true
                    value: ~
                    option:
                        label: librinfo.label.product_option
            # FILTERS
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    translations.value:
                        label: librinfo.label.value
