services:    
# ENTITY CODE GENERATORS

    librinfo_ecommerce.code_generator.product:
        class: Librinfo\EcommerceBundle\CodeGenerator\ProductCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%librinfo_ecommerce.code_generator.product%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    librinfo_ecommerce.code_generator.product_variant:
        class: Librinfo\EcommerceBundle\CodeGenerator\ProductVariantCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%librinfo_ecommerce.code_generator.product_variant%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

# EVENT LISTENERS

    librinfo_ecommerce.listener.sylius_guidable:
        class: Librinfo\EcommerceBundle\EventListener\SyliusGuidableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger, [@logger]]
            - [setClassAnalyser, [Blast\CoreBundle\Tools\Reflection\ClassAnalyzer]]
            
    librinfo_ecommerce.listener.address:
        class: Librinfo\EcommerceBundle\EventListener\AddressListener
        tags:
            - { name: doctrine.event_subscriber }

# USER BUNDLE OVERRIDES
    
    librinfo_user.listener.traceable:
        class: Librinfo\EcommerceBundle\EventListener\TraceableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setTokenStorage, [@security.token_storage]]
            - [setUserClass, [Librinfo\EcommerceBundle\Entity\AdminUser]]
            - [setClassAnalyser, [Blast\CoreBundle\Tools\Reflection\ClassAnalyzer]]

    librinfo_user.listener.ownable:
        class: Librinfo\UserBundle\EventListener\OwnableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setTokenStorage, [@security.token_storage]]
            - [setUserClass, [Librinfo\EcommerceBundle\Entity\AdminUser]]
            - [setClassAnalyser, [Blast\CoreBundle\Tools\Reflection\ClassAnalyzer]]