services:

# ENTITY CODE GENERATORS

    librinfo_ecommerce.code_generator.product:
        class: Librinfo\EcommerceBundle\CodeGenerator\ProductCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%librinfo_ecommerce.code_generator.product%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    librinfo_ecommerce.code_generator.product_variant:
        class: Librinfo\EcommerceBundle\CodeGenerator\ProductVariantCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%librinfo_ecommerce.code_generator.product_variant%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }
            
# FORM TYPE EXTENSIONS            
#    librinfo_ecommerce.extension.type.customer_registration:
#        class: Librinfo\EcommerceBundle\Form\Extension\CustomerRegistrationTypeExtension
#        tags:
#            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType }