Sylius\Component\Product\Model\ProductTranslation:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: slug
            message: sil.product_slug.not_unique
    properties:
        slug:
            - NotBlank:
                message: sil.product_slug.empty
            - Length:
                min: 3
                minMessage: sil.product_slug.too_short
                max: 255
                maxMessage: sil.product_slug.too_long
        name:
            - NotBlank:
                message: sil.product_name.empty
            - Length:
                min: 3
                minMessage: sil.product_name.too_short
                max: 255
                maxMessage: sil.product_name.too_long

Sil\Bundle\EcommerceBundle\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - NotBlank: ~
        translations:
            - Valid: ~
