Sylius\Component\Product\Model\ProductTranslation:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: slug
            message: lisem.product_slug.not_unique
    properties:
        slug:
            - NotBlank:
                message: lisem.product_slug.empty
            - Length:
                min: 3
                minMessage: lisem.product_slug.too_short
                max: 255
                maxMessage: lisem.product_slug.too_long
        name:
            - NotBlank:
                message: lisem.product_name.empty
            - Length:
                min: 3
                minMessage: lisem.product_name.too_short
                max: 255
                maxMessage: lisem.product_name.too_long

Librinfo\EcommerceBundle\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - NotBlank: ~
        translations:
            - Valid: ~
