
services:
    sil_ecommerce_option.admin.product:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductOptionAdmin
        arguments: [~, "%sil_ecommerce.entity.product_option.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.product.product_option
                label_translator_strategy: blast_core.label.strategy.sil_ecommerce
