
services:
    sil_ecommerce.admin.channel:
        class: Sil\Bundle\EcommerceBundle\Admin\ChannelAdmin
        arguments: [~, "%sil_ecommerce.entity.channel.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.channel
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
