
services:
    sil_ecommerce.admin.tax_rate:
        class: Sil\Bundle\EcommerceBundle\Admin\TaxRateAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\TaxRate, BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.TaxRate
                label_translator_strategy: blast_core.label.strategy.sil_ecommerce
