
services:
    sil_ecommerce.admin.order:
        class: Sil\Bundle\EcommerceBundle\Admin\OrderAdmin
        arguments: [~, "%sil_ecommerce.entity.order.class%", SilEcommerceBundle:OrderCRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.order
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [edit, SilEcommerceBundle:OrderAdmin/Create:create.html.twig]]
