
services:
    sil_ecommerce.admin.product_attribute:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductAttributeAdmin
        arguments: [~, "%sil_ecommerce.entity.product_attribute.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.product_attribute
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
