
services:
    sil_ecommerce.admin.product_variant_embedded:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductVariantEmbeddedAdmin
        arguments: [~, "%sil_ecommerce.entity.product_variant.class%", SilEcommerceBundle:ProductVariantCRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.product.product_variant
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]
