
services:
    sil_ecommerce.admin.product_variant_embedded:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductVariantEmbeddedAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\ProductVariant, SilEcommerceBundle:ProductVariantCRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.product.product_variant
                label_translator_strategy: blast_core.label.strategy.sil_ecommerce
        calls:
            - [ setTemplate, [ edit, SilEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]
