
services:
    sil_ecommerce.admin.shipping_method_translation:
        class: Sil\Bundle\EcommerceBundle\Admin\ShippingMethodTranslationAdmin
        arguments: [~, "%sylius.model.shipping_method_translation.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.shipping_method_translation
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
