
services:
    sil_ecommerce_option_value.admin.product:
        class: Sil\Bundle\EcommerceBundle\Admin\ProductOptionValueAdmin
        arguments: [~, "%sil_ecommerce.entity.product_option_value.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.product.product_option_value
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
