
services:
    sil_ecommerce.admin.shipping_method:
        class: Sil\Bundle\EcommerceBundle\Admin\ShippingMethodAdmin
        arguments: [~, "%sil_ecommerce.entity.shipping_method.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.shipping_method
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix

#    sil_ecommerce.admin.shipping_category:
#        class: Sil\Bundle\EcommerceBundle\Admin\ShippingCategoryAdmin
#        arguments: [~, Sylius\Component\Shipping\Model\ShippingCategory, BlastCoreBundle:CRUD]
#        tags:
#            - name: sonata.admin
#              manager_type: orm
#              group: admin
#              label: sil.ecommerce.menu_label.shipping_category
#              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
