
services:
    sil_ecommerce.admin.tax_rate:
        class: Sil\Bundle\EcommerceBundle\Admin\TaxRateAdmin
        arguments: [~, "%sil_ecommerce.entity.tax_rate.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.TaxRate
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
