
services:
    sil_ecommerce.admin.shop_user:
        class: Sil\Bundle\EcommerceBundle\Admin\ShopUserAdmin
        arguments: [~, "%sylius.model.shop_user.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.shop_user
                label_translator_strategy: blast_core.label.strategy.sil_ecommerce
