
services:
    sil_ecommerce.admin.tax_rate:
        class: Sil\Bundle\EcommerceBundle\Admin\TaxRateAdmin
        arguments: [~, "%sil.model.ecommerce_tax_rate.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.tax_rate
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
