
services:
    sil_ecommerce.admin.sales_journal:
        class: Sil\Bundle\EcommerceBundle\Admin\SalesJournalAdmin
        arguments: [~, "%sil_ecommerce.entity.sales_journal_item.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.sales_journal
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
