
services:
    sil_ecommerce.admin.invoice:
        class: Sil\Bundle\EcommerceBundle\Admin\InvoiceAdmin
        arguments: [~, "%sil_ecommerce.entity.invoice.class%", SilEcommerceBundle:InvoiceCRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.Invoice
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
