
services:
    sil_ecommerce.admin.taxon:
        class: Sil\Bundle\EcommerceBundle\Admin\TaxonAdmin
        arguments: [~, "%sil_ecommerce.entity.taxon.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.taxon
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
