
services:
    sil_ecommerce.admin.invoice:
        class: Sil\Bundle\EcommerceBundle\Admin\InvoiceAdmin
        arguments: [~, "%sil.model.ecommerce_invoice.class%", SilEcommerceBundle:InvoiceCRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.invoice
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
