
services:
    sil_ecommerce.admin.payment_method:
        class: Sil\Bundle\EcommerceBundle\Admin\PaymentMethodAdmin
        arguments: [~, "%sylius.model.payment_method.class%", SilEcommerceBundle:PaymentCRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommercebundle.admin.payment_method
                label_translator_strategy: blast_core.label.strategy.sil_ecommerce
