
services:
    sil_ecommerce.admin.customer_group:
        class: Sil\Bundle\EcommerceBundle\Admin\CustomerGroupAdmin
        arguments: [~, Sil\Bundle\EcommerceBundle\Entity\CustomerGroup, BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.ecommercebundle.admin.customer_group
                label_translator_strategy: blast_core.label.strategy.sil_ecommerce
