
services:
    sil_ecommerce.admin.zone:
        class: Sil\Bundle\EcommerceBundle\Admin\ZoneAdmin
        arguments: [~, "%sil.model.ecommerce_zone.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.zone
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
