
services:
    sil_ecommerce.admin.channel_pricing:
        class: Sil\Bundle\EcommerceBundle\Admin\ChannelPricingAdmin
        arguments: [~, "%sylius.model.channel_pricing.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.ecommerce.menu_label.channel
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
