# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

    librinfo_ecommerce.admin.product:
        class: Librinfo\EcommerceBundle\Admin\ProductAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\Product, LibrinfoEcommerceBundle:ProductCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductAdmin:edit.html.twig ] ]

    librinfo_ecommerce.admin.product_variant:
        class: Librinfo\EcommerceBundle\Admin\ProductVariantAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductVariant, LibrinfoEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_variant_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]

    librinfo_ecommerce.admin.product_variant_embedded:
        class: Librinfo\EcommerceBundle\Admin\ProductVariantEmbeddedAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductVariant, LibrinfoEcommerceBundle:ProductVariantCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_variant_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoEcommerceBundle:ProductVariantAdmin:edit.html.twig ] ]

    librinfo_ecommerce_option.admin.product:
        class: Librinfo\EcommerceBundle\Admin\ProductOptionAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductOption, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_option_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce_option_value.admin.product:
        class: Librinfo\EcommerceBundle\Admin\ProductOptionValueAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductOptionValue, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_option_value_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.product_attribute:
        class: Librinfo\EcommerceBundle\Admin\ProductAttributeAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\ProductAttribute, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.product.product_attribute_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.customer:
        class: Librinfo\EcommerceBundle\Admin\CustomerAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoCRMBundle:OrganismAdmin]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Customers Relationship Management
              label: librinfo.crm.customer_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [setCodeGenerator, ['@librinfo_crm.code_generator.customer']]
            - [ setTemplate, [edit, LibrinfoCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]

    librinfo_ecommerce.admin.order:
        class: Librinfo\EcommerceBundle\Admin\OrderAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\Order, LibrinfoEcommerceBundle:OrderCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.label.order_admin
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.payment:
        class: Librinfo\EcommerceBundle\Admin\PaymentAdmin
        arguments: [~, Sylius\Component\Core\Model\Payment, LibrinfoEcommerceBundle:PaymentCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.label.payment_admin
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.payment_method:
        class: Librinfo\EcommerceBundle\Admin\PaymentMethodAdmin
        arguments: [~, Sylius\Component\Core\Model\PaymentMethod, LibrinfoEcommerceBundle:PaymentCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.label.payment_method_admin
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.sales_journal:
        class: Librinfo\EcommerceBundle\Admin\SalesJournalAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\Order, LibrinfoEcommerceBundle:OrderCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.label.sales_journal
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.customer_group:
        class: Librinfo\EcommerceBundle\Admin\CustomerGroupAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\CustomerGroup, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Customers Relationship Management
              label: librinfo.label.customer_group_admin
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.channel_pricing:
        class: Librinfo\EcommerceBundle\Admin\ChannelPricingAdmin
        arguments: [~, Sylius\Component\Core\Model\ChannelPricing, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: Channel
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.tax_rate:
        class: Librinfo\EcommerceBundle\Admin\TaxRateAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\TaxRate, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: TaxRate
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.tax_category:
        class: Librinfo\EcommerceBundle\Admin\TaxCategoryAdmin
        arguments: [~, Sylius\Component\Taxation\Model\TaxCategory, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: TaxCategory
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_ecommerce.admin.zone:
        class: Blast\CoreBundle\Admin\GenericAdmin
        arguments: [~, Librinfo\EcommerceBundle\Entity\Zone, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: Zone
              label_translator_strategy: blast_core.label.strategy.librinfo
