services:
# ENTITY CODE GENERATORS

    librinfo_ecommerce.code_generator.product:
        class: Librinfo\EcommerceBundle\CodeGenerator\ProductCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%librinfo_ecommerce.code_generator.product%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    librinfo_ecommerce.code_generator.product_variant:
        class: Librinfo\EcommerceBundle\CodeGenerator\ProductVariantCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%librinfo_ecommerce.code_generator.product_variant%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

    librinfo_ecommerce.code_generator.invoice:
        class: Librinfo\EcommerceBundle\CodeGenerator\InvoiceCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%librinfo_ecommerce.code_generator.invoice%', '@doctrine.orm.entity_manager']
        tags:
            - { name: blast.entity_code_generator }

# FORM TYPES

    librinfo_ecommerce.form.type.order_state:
        class: Librinfo\EcommerceBundle\Form\Type\OrderStateType
        tags:
            - { name: form.type, alias: librinfo_type_order_state }

    librinfo_ecommerce.form.type.payment_state:
        class: Librinfo\EcommerceBundle\Form\Type\PaymentStateType
        tags:
            - { name: form.type, alias: librinfo_type_payment_state }

    librinfo_ecommerce.form.type.shipping_state:
        class: Librinfo\EcommerceBundle\Form\Type\ShippingStateType
        tags:
            - { name: form.type, alias: librinfo_type_shipping_state }

    librinfo_ecommerce.form.type.price_cents:
        class: Librinfo\EcommerceBundle\Form\Type\PriceCentsType
        tags:
            - { name: form.type, alias: librinfo_type_price_cents }

    librinfo_ecommerce.form.type.taxon_list:
        class: Librinfo\EcommerceBundle\Form\Type\TaxonListType
        tags:
            - { name: form.type, alias: librinfo_type_taxon_list }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%sylius.model.taxon.class%'

    librinfo_ecommerce.form.type.product_taxon_list:
        class: Librinfo\EcommerceBundle\Form\Type\ProductTaxonListType
        tags:
            - { name: form.type, alias: librinfo_type_product_taxon_list }
        arguments:
            # - '@property_accessor'
            - '@doctrine.orm.entity_manager'
            - '%sylius.model.product_taxon.class%'
            - '%sylius.model.taxon.class%'

    librinfo_ecommerce.form.type.product_channels:
        class: Librinfo\EcommerceBundle\Form\Type\ProductChannelsType
        tags:
            - { name: form.type, alias: librinfo_type_product_channels }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%sylius.model.channel.class%'
            - '%sylius.model.product.class%'

# EMAIL MANAGERS

    librinfo_ecommerce.email_manager.order:
        class: Librinfo\EcommerceBundle\EmailManager\OrderEmailManager
        arguments:
            - '@sylius.email_sender'
            - '@librinfo_ecommerce.factory.invoice'
            - '@doctrine.orm.entity_manager'

# ORDER CUSTOMER MANAGER

    librinfo_ecommerce.order_customer_manager:
        class: Librinfo\EcommerceBundle\Services\OrderCustomerManager
        arguments:
            - '@doctrine.orm.entity_manager'

# EVENT LISTENERS

    librinfo_ecommerce.listener.sylius_guidable:
        class: Librinfo\EcommerceBundle\EventListener\SyliusGuidableListener
        tags:
            - { name: doctrine.event_subscriber, priority: -10 }
        calls:
            - [setLogger, ['@logger']]
            - [setClassAnalyser, [Blast\CoreBundle\Tools\Reflection\ClassAnalyzer]]

    # service override
    sylius.listener.order_complete:
        class: Librinfo\EcommerceBundle\EventListener\OrderCompleteListener
        tags:
            - { name: kernel.event_listener, event: sylius.order.post_complete, method: sendConfirmationEmail }
        arguments:
            - '@librinfo_ecommerce.email_manager.order'



# SYLIUS INSTALLER

    librinfo_ecommerce.sylius.setup.currency:
        class: Librinfo\EcommerceBundle\Services\Sylius\Setup\CurrencySetup
        arguments:
            - '@sylius.repository.currency'
            - '@sylius.factory.currency'
            - '%currency%'

# SYLIUS FACTORIES

    librinfo_ecommerce.sylius.factory.customer:
        class: Librinfo\EcommerceBundle\Factory\CustomerFactory
        decorates: 'sylius.factory.customer'
        public: false
        arguments:
            - '@librinfo_ecommerce.sylius.factory.customer.inner'
            - '@librinfo_crm.code_generator.customer'

    librinfo_ecommerce.factory.invoice:
        class: Librinfo\EcommerceBundle\Factory\InvoiceFactory
        arguments:
            - '@librinfo_ecommerce.code_generator.invoice'
            - '@knp_snappy.pdf'
            - '@templating'
            - '%librinfo_ecommerce.invoice.template%'
            - '%kernel.root_dir%'

# SYLIUS FIXTURES & FIXTURE FACTORIES

    librinfo_ecommerce.sylius.fixture.channel:
        class: Librinfo\EcommerceBundle\Fixture\ChannelFixture
        arguments:
            - '@sylius.manager.channel'
            - '@librinfo_ecommerce.sylius.fixture.example_factory.channel'
        tags:
            - { name: sylius_fixtures.fixture }

    librinfo_ecommerce.sylius.fixture.customer:
        class: Librinfo\EcommerceBundle\Fixture\CustomerFixture
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@librinfo_crm.code_generator.customer'
        tags:
            - { name: sylius_fixtures.fixture }

    librinfo_ecommerce.sylius.fixture.example_factory.channel:
        class: Librinfo\EcommerceBundle\Fixture\Factory\ChannelExampleFactory
        arguments:
            - '@sylius.factory.channel'
            - '@sylius.repository.locale'
            - '@sylius.repository.currency'
            - '@sylius.repository.zone'


# USER BUNDLE OVERRIDES

# TODO: refactor this since it does not work well with SonataSyliusUserBundle

#    librinfo_user.listener.traceable:
#        class: Librinfo\EcommerceBundle\EventListener\TraceableListener
#        tags:
#            - { name: doctrine.event_subscriber }
#        calls:
#            - [setLogger,['@logger']]
#            - [setTokenStorage, ['@security.token_storage']]
#            - [setUserClass, [Librinfo\EcommerceBundle\Entity\AdminUser]]
#            - [setClassAnalyser, [Blast\CoreBundle\Tools\Reflection\ClassAnalyzer]]
#
#    librinfo_user.listener.ownable:
#        class: Librinfo\SonataSyliusUserBundle\EventListener\OwnableListener
#        tags:
#            - { name: doctrine.event_subscriber }
#        calls:
#            - [setLogger,['@logger']]
#            - [setTokenStorage, ['@security.token_storage']]
#            - [setUserClass, [Librinfo\EcommerceBundle\Entity\AdminUser]]
#            - [setClassAnalyser, [Blast\CoreBundle\Tools\Reflection\ClassAnalyzer]]

    imagine.data.loader.resolver.default:
        class: Librinfo\EcommerceBundle\Imagine\PathResolver\ProductPathResolver
        calls:
            - [setEm, ['@doctrine.orm.entity_manager'] ]
            - [setWebDir, ['%assetic.read_from%'] ]

    librinfo_ecommerce.media.events.listener:
        class: Librinfo\EcommerceBundle\EventListener\UploadControllerEventListener
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]
        tags:
            - { name: kernel.event_listener, event: librinfo.events.media   .load.preGetEntity, method: preGetEntity, priority: -10 }
            - { name: kernel.event_listener, event: librinfo.events.media.load.postGetEntity, method: postGetEntity, priority: -10 }

    librinfo_ecommerce.order.updater:
        class: Librinfo\EcommerceBundle\Services\OrderUpdater
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sylius.context.channel'
#            - '@sylius.money_formatter'
            - '@sylius.factory.order_item'
            - '@sylius.factory.order_item_unit'

    librinfo_ecommerce.order.item_updater:
        class: Librinfo\EcommerceBundle\Services\OrderItemUpdater
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sylius.order_item_quantity_modifier'
            - '@sylius.money_formatter'
            - '%sylius.model.order_item.class%'

    librinfo_ecommerce.dashboard.main_block:
        class: Librinfo\EcommerceBundle\Dashboard\EcommerceDashboardBlock
        arguments:
            - librinfo_ecommerce.dashboard.main_block
            - "@templating"
        tags:
            - { name: sonata.block }
