# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

doctrine:
    orm:
        mappings:
            SyliusProductBundle:
                type: xml
                prefix: Sylius\Component\Product\Model
                dir: Resources/config/doctrine/model

sylius_product:
    driver: doctrine/orm
    resources:
        product:
            classes:
                model: Librinfo\EcommerceBundle\Entity\Product
        product_variant:
            classes:
                model: Librinfo\EcommerceBundle\Entity\ProductVariant
        product_option:
            classes:
                model: Librinfo\EcommerceBundle\Entity\ProductOption
        product_option_value:
            classes:
                model: Librinfo\EcommerceBundle\Entity\ProductOptionValue

sylius_attribute:
    resources:
        product:
            subject: Librinfo\EcommerceBundle\Entity\Product
            attribute:
                classes:
                    model: Librinfo\EcommerceBundle\Entity\ProductAttribute

#sylius_product_association:
#    resources:
#        product:
#            subject: Librinfo\EcommerceBundle\Entity\Product
#            association:
#                classes:
#                    model: Sylius\Component\Product\Model\ProductAssociation
#                    interface: Sylius\Component\Product\Model\ProductAssociationInterface
