# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

doctrine:
    orm:
        mappings:
            SyliusProductBundle:
                type: xml
                prefix: Sylius\Component\Product\Model
                dir: Resources/config/doctrine/model

sylius_product:
    driver: doctrine/orm
    resources:
        product:
            classes:
                model: Librinfo\EcommerceBundle\Entity\Product
        product_variant:
            classes:
                model: Librinfo\EcommerceBundle\Entity\ProductVariant
        product_option:
            classes:
                model: Librinfo\EcommerceBundle\Entity\ProductOption
        product_option_value:
            classes:
                model: Librinfo\EcommerceBundle\Entity\ProductOptionValue
                
sylius_order:
    resources:
        order:
            classes:
                model: Librinfo\EcommerceBundle\Entity\Order
                
sylius_taxation:
    resources:
        tax_rate:
            classes:
                model: Librinfo\EcommerceBundle\Entity\TaxRate
                
                
sylius_channel:
    driver: doctrine/orm
    resources:
        channel:
            classes:
                repository: Librinfo\EcommerceBundle\Repository\ChannelRepository

sylius_attribute:
    resources:
        product:
            subject: Librinfo\EcommerceBundle\Entity\Product
            attribute:
                classes:
                    model: Librinfo\EcommerceBundle\Entity\ProductAttribute

sylius_customer:
    driver: doctrine/orm
    resources:
        customer:
            classes:
                model: Librinfo\CRMBundle\Entity\Organism
        customer_group:
            classes:
                model: Librinfo\EcommerceBundle\Entity\CustomerGroup

sylius_addressing:
    resources:
        address:
            classes:
                model: Librinfo\CRMBundle\Entity\Address
        zone:
            classes:
                model: Librinfo\EcommerceBundle\Entity\Zone

sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: Librinfo\SonataSyliusUserBundle\Entity\SonataUser

sylius_core:
    resources:
        product_image:
            classes:
                model: Librinfo\EcommerceBundle\Entity\ProductImage

fos_rest:
    exception: ~
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
        
#    # « format_listener » Conflicts with Sylius configuration
#
#    format_listener:
#        rules:
#            -   path: '^/api'
#                priorities: [json, xml]
#                fallback_format: json
#                prefer_extension: true
#            -   path: '^/'
#                stop: true

#sylius_product_association:
#    resources:
#        product:
#            subject: Librinfo\EcommerceBundle\Entity\Product
#            association:
#                classes:
#                    model: Sylius\Component\Product\Model\ProductAssociation
#                    interface: Sylius\Component\Product\Model\ProductAssociationInterface