winzou_state_machine:
    sylius_order:
        transitions:
            cancel:
                from: [new, fulfilled]
                to: cancelled
        callbacks:
            before:
                sylius_save_addresses_on_customer:
                    on:   ["create"]
                    do:   ["@librinfo_ecommerce.order_customer_manager", "associateUserAndAddress"]
                    args: ["object"]
            after:
                librinfo_ecommerce_order_validated:
                    on:   ["create"]
                    do:   ["@librinfo_ecommerce.order_state_manager", "validateOrder"]
                    args: ["object"]
