winzou_state_machine:
    sylius_order:
        transitions:
            cancel:
                from: [fulfilled]
                to: cancelled
        callbacks:
            before:
                sylius_save_addresses_on_customer:
                    on:   ["create"]
                    do:   ["@librinfo_ecommerce.order_customer_manager", "associateUserAndAddress"]
                    args: ["object"]
            after:
                librinfo_ecommerce_order_validated:
                    on:   ["create","fulfill"]
                    do:   ["@librinfo_ecommerce.order_manager", "validateOrder"]
                    args: ["object"]
                librinfo_ecommerce_order_generate_credit_note:
                    on:   ["cancel"]
                    do:   ["@librinfo_ecommerce.order_manager", "generateCreditInvoice"]
                    args: ["object"]
