winzou_state_machine:
    sylius_order:
        # transitions:
        #     restaure:
        #         from: [cancelled]
        #         to: new
        callbacks:
            before:
                sylius_save_addresses_on_customer:
                    on: ["create"]
                    do: ["@librinfo_ecommerce.order_customer_manager", "associateUserAndAddress"]
                    args: ["object"]
