Librinfo\CRMBundle\Entity\Address:
    type: entity
    manyToOne:
        organism:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            inversedBy: addresses
            joinColumn:
                name: organism_id
            cascade: [ persist ]
