Librinfo\EcommerceBundle\Entity\ProductImage:
    type: entity
    manyToOne:
        realFile:
            targetEntity: Librinfo\MediaBundle\Entity\File
    manyToMany:
        productVariants:
            targetEntity: Librinfo\EcommerceBundle\Entity\ProductVariant
            orphanRemoval: true
            joinTable: 
                name: librinfo_ecommerce_productimage__productvariants
                joinColumns:
                    joinColumn:
                        name: image_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    joinColumn:
                        name: variant_id
                        referencedColumnName: id
                        onDelete: CASCADE